[package]
name = "draco-api"
authors = ["Logan Koester <logan@logankoester.com>"]
version = "0.1.0"
homepage = "https://smaug.dev/packages/draco-api"
keywords = []

# Optional:
# documentation = "https://example.com"
repository = "https://github.com/ereborstudios/draco-api"

requires = [
  "smaug/draco-api/lib/set.rb",
  "smaug/draco-api/lib/docile.rb",
  "smaug/draco-api/lib/router/index.rb",
  "smaug/draco-api/lib/api.rb",
  "smaug/draco-api/lib/encoder.rb",
  "app/components/draco-api/index.rb",
  "app/entities/draco-api/index.rb",
  "app/systems/draco-api/index.rb",
]

[package.installs]
"templates/app/components/match.rb" = "app/components/draco-api/match.rb"
"templates/app/components/response.rb" = "app/components/draco-api/response.rb"
"templates/app/components/tree.rb" = "app/components/draco-api/tree.rb"
"templates/app/components/index.rb" = "app/components/draco-api/index.rb"

"templates/app/entities/route.rb" = "app/entities/draco-api/route.rb"
"templates/app/entities/index.rb" = "app/entities/draco-api/index.rb"

"templates/app/systems/api_router.rb" = "app/systems/draco-api/api_router.rb"
"templates/app/systems/index.rb" = "app/systems/draco-api/index.rb"

[dragonruby]
version = "2"
edition = "standard"
