# This file was automatically @generated by Smaug.
# Do not manually edit this file. Edit Smaug.toml instead.

require "smaug/draco/lib/draco.rb"
require "smaug/draco-api/lib/set.rb"
require "smaug/draco-api/lib/docile.rb"
require "smaug/draco-api/lib/router/index.rb"
require "smaug/draco-api/lib/api.rb"
require "smaug/draco-api/lib/encoder.rb"
require "app/components/draco-api/index.rb"
require "app/entities/draco-api/index.rb"
require "app/systems/draco-api/index.rb"

require "app/components/index.rb"
require "app/entities/index.rb"
require "app/systems/index.rb"
require "app/worlds/index.rb"
